server:
  port: 9011
spring:
  application:
    name: tourreservation-service
  datasource:
    url: jdbc:mysql://localhost:3306/destinationreservation?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  mvc:
    hiddenmethod:
      filter:
        enabled=true: