server:
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
