server:
  port: 9002
spring:
  application:
    name: reservation-service
  datasource:
    url: jdbc:mysql://localhost:3306/reservation?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka