
#jwt:
#  secret : ekqpreuorqiueriqeurpeqruqoruoqure

server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      # 회원서비스
      routes:
        - id: auth-service
          uri: "lb://AUTH-SERVICE"
          predicates:
            - Path=/api/v1/auth/**
      # 찾는 서비스
        - id: find-service
          uri: "lb://FIND-SERVICE"
          predicates:
            - Path=/api/v1/find/**
#          filters:
#            - name: "TokenFilter"
#              args:
#                logging: false

        # 예약 서비스
        - id: reservation-service
          uri: "lb://RESERVATION-SERVICE"
          predicates:
            - Path=/api/v1/reservation/**
#        #결제 서비스
#        - id: payment-service
#          uri: "lb://PAYMENT-SERVICE"
#          predicates:
#            - Path=/api/v1/payment/**
        #결제 서비스
        - id: customer-service
          uri: "lb://RESERVATION-SERVICE"
          predicates:
            - Path=/api/v1/customer/**

#          filters:
#            - name: "TokenFilter"
        #관광명소 서비스
        - id: TD-service
          uri: "lb://TOUR-SERVICE"
          predicates:
            - Path=/api/v1/tourdestination/**

        # 관광명소예약 서비스
        - id: TD-reservation-service
          uri: "lb://TOURRESERVATION-SERVICE"
          predicates:
            - Path=/api/v1/tourdestinationreservation/**




eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
